In [3]:
##Student_Performance_Analytics

import pandas as pd
df_student = pd.read_csv(r"C:\Users\anmol\Downloads\student_performance_project.csv")

df_student

    StudentID             Name Gender       City  Math  Science  English
0           1     Aditi Sharma      F  Bengaluru  33.0     33.0     74.0
1           2      Rohan Verma      F     Mumbai  78.0     97.0     60.0
2           3       Meera Nair      F      Delhi  90.0     81.0     70.0
3           4      Karan Mehta      F      Delhi  45.0     41.0     70.0
4           5        Sneha Rao      M      Delhi  91.0     80.0     51.0
..        ...              ...    ...        ...   ...      ...      ...
56         57     Qasim Sheikh      M      Delhi  49.0     55.0     91.0
57         58  Reema Chowdhury      F    Kolkata  61.0     47.0     33.0
58         59     Sahil Kapoor      M       Pune  60.0     59.0     34.0
59         60    Tara Krishnan      F    Chennai  79.0      NaN     81.0
60          1     Aditi Sharma      F  Bengaluru  33.0     33.0     74.0

[61 rows x 7 columns]

In [5]:
##Data Quality

print(df_student.head())
print(df_student.tail())

   StudentID          Name Gender       City  Math  Science  English
0          1  Aditi Sharma      F  Bengaluru  33.0     33.0     74.0
1          2   Rohan Verma      F     Mumbai  78.0     97.0     60.0
2          3    Meera Nair      F      Delhi  90.0     81.0     70.0
3          4   Karan Mehta      F      Delhi  45.0     41.0     70.0
4          5     Sneha Rao      M      Delhi  91.0     80.0     51.0
    StudentID             Name Gender       City  Math  Science  English
56         57     Qasim Sheikh      M      Delhi  49.0     55.0     91.0
57         58  Reema Chowdhury      F    Kolkata  61.0     47.0     33.0
58         59     Sahil Kapoor      M       Pune  60.0     59.0     34.0
59         60    Tara Krishnan      F    Chennai  79.0      NaN     81.0
60          1     Aditi Sharma      F  Bengaluru  33.0     33.0     74.0

In [17]:
df_student.info()
df_student.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 50 entries, 0 to 58
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   StudentID  50 non-null     int64
 1   Name       50 non-null     object
 2   Gender     50 non-null     object
 3   City       50 non-null     object
 4   Math       50 non-null     float64
 5   Science    50 non-null     float64
 6   English    50 non-null     float64
dtypes: float64(3), int64(1), object(3)
memory usage: 3.1+ KB

       StudentID       Math    Science    English
count  50.000000  50.000000  50.000000  50.000000
mean   29.900000  60.980000  65.040000  62.740000
std    17.152676  20.233827  18.099453  19.078581
min     1.000000  30.000000  31.000000  30.000000
25%    16.250000  47.250000  49.750000  47.250000
50%    30.500000  57.500000  65.500000  63.000000
75%    44.500000  78.750000  79.250000  73.750000
max    59.000000  98.000000  98.000000  96.000000

In [7]:
print(df_student.isnull().sum())

StudentID    0
Name         0
Gender       0
City         0
Math         4
Science      3
English      3
dtype: int64

In [10]:
df_student.dropna(inplace = True)
print(df_student.isnull().sum())

StudentID    0
Name         0
Gender       0
City         0
Math         0
Science      0
English      0
dtype: int64

In [11]:
print(df_student.duplicated())

0     False
1     False
2     False
3     False
4     False
5     False
7     False
8     False
10    False
11    False
12    False
13    False
15    False
16    False
17    False
18    False
19    False
20    False
22    False
23    False
24    False
25    False
26    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
41    False
42    False
44    False
45    False
46    False
47    False
48    False
49    False
50    False
51    False
53    False
55    False
56    False
57    False
58    False
60     True
dtype: bool

In [13]:
df_student.drop_duplicates(subset = ["Name"], keep = "first", inplace = True)

In [14]:
print(df_student.duplicated())

0     False
1     False
2     False
3     False
4     False
5     False
7     False
8     False
10    False
11    False
12    False
13    False
15    False
16    False
17    False
18    False
19    False
20    False
22    False
23    False
24    False
25    False
26    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
41    False
42    False
44    False
45    False
46    False
47    False
48    False
49    False
50    False
51    False
53    False
55    False
56    False
57    False
58    False
dtype: bool

In [20]:
##Filtering Students


df_student[(df_student["Math"] < 40) | (df_student["Science"] < 40) | (df_student["English"] < 40)]

    StudentID              Name Gender       City  Math  Science  English
0           1      Aditi Sharma      F  Bengaluru  33.0     33.0     74.0
5           6       Arjun Singh      F     Mumbai  35.0     47.0     63.0
12         13       Ishita Bose      F    Chennai  45.0     36.0     83.0
17         18    Siddharth Rana      M    Kolkata  80.0     39.0     96.0
19         20      Yash Agarwal      F  Bengaluru  47.0     55.0     37.0
20         21        Ritu Bhatt      M    Kolkata  30.0     70.0     31.0
22         23      Sanya Khanna      M  Bengaluru  31.0     74.0     52.0
24         25      Kavya Pillai      F    Kolkata  46.0     31.0     72.0
28         29        Riya Sinha      F       Pune  64.0     41.0     35.0
32         33    Swati Deshmukh      F    Chennai  36.0     94.0     38.0
35         36       Kunal Dutta      M  Bengaluru  76.0     53.0     30.0
39         40        Om Prakash      M    Kolkata  39.0     47.0     59.0
41         42       Bela Shetty      M    Kolkata  32.0     80.0     45.0
44         45  Eshan Chatterjee      M       Pune  30.0     77.0     57.0
57         58   Reema Chowdhury      F    Kolkata  61.0     47.0     33.0
58         59      Sahil Kapoor      M       Pune  60.0     59.0     34.0

In [18]:
##Subject wise analysis


df_student[["Math", "Science", "English"]].agg(["max", "min", "mean"]).round(2)

       Math  Science  English
max   98.00    98.00    96.00
min   30.00    31.00    30.00
mean  60.98    65.04    62.74

In [26]:
##Total, Average and ranking

df_student["Total"] = df_student[["Math", "Science", "English"]].sum(axis=1)

df_student["Average"] = df_student[["Math", "Science", "English"]].mean(axis=1).round(2)

df_student["Rank"] = df_student["Total"].rank(ascending=False)

df_student

,StudentID,Name,Gender,City,Math,Science,English,Total,Average,Rank
0,1,Aditi Sharma,F,Bengaluru,33.0,33.0,74.0,140.0,46.67,47.5
1,2,Rohan Verma,F,Mumbai,78.0,97.0,60.0,235.0,78.33,5.0
2,3,Meera Nair,F,Delhi,90.0,81.0,70.0,241.0,80.33,4.0
3,4,Karan Mehta,F,Delhi,45.0,41.0,70.0,156.0,52.00,41.0
4,5,Sneha Rao,M,Delhi,91.0,80.0,51.0,222.0,74.00,7.0
5,6,Arjun Singh,F,Mumbai,35.0,47.0,63.0,145.0,48.33,44.5
7,8,Vikram Joshi,F,Delhi,48.0,65.0,83.0,196.0,65.33,19.0
8,9,Anjali Gupta,F,Bengaluru,49.0,77.0,49.0,175.0,58.33,33.0
10,11,Divya Menon,M,Mumbai,82.0,45.0,65.0,192.0,64.00,24.0
11,12,Kabir Malik,F,Mumbai,56.0,85.0,52.0,193.0,64.33,22.5
12,13,Ishita Bose,F,Chennai,45.0,36.0,83.0,164.0,54.67,36.5
13,14,Farhan Sheikh,M,Chennai,47.0,93.0,51.0,191.0,63.67,25.0
15,16,Aman Trivedi,F,Pune,57.0,69.0,68.0,194.0,64.67,21.0
16,17,Pooja Iyer,M,Chennai,97.0,60.0,64.0,221.0,73.67,8.0
17,18,Siddharth Rana,M,Kolkata,80.0,39.0,96.0,215.0,71.67,11.0
18,19,Tanvi Shah,M,Pune,60.0,86.0,73.0,219.0,73.00,9.0
19,20,Yash Agarwal,F,Bengaluru,47.0,55.0,37.0,139.0,46.33,49.0
20,21,Ritu Bhatt,M,Kolkata,30.0,70.0,31.0,131.0,43.67,50.0
22,23,Sanya Khanna,M,Bengaluru,31.0,74.0,52.0,157.0,52.33,39.5
23,24,Dev Saxena,M,Mumbai,58.0,74.0,61.0,193.0,64.33,22.5
24,25,Kavya Pillai,F,Kolkata,46.0,31.0,72.0,149.0,49.67,43.0
25,26,Nikhil Bhatia,M,Kolkata,98.0,47.0,42.0,187.0,62.33,27.0
26,27,Simran Kaur,M,Mumbai,98.0,66.0,45.0,209.0,69.67,13.0
28,29,Riya Sinha,F,Pune,64.0,41.0,35.0,140.0,46.67,47.5
29,30,Varun Oberoi,M,Kolkata,79.0,65.0,69.0,213.0,71.00,12.0
30,31,Ananya Pandey,F,Mumbai,59.0,54.0,63.0,176.0,58.67,32.0
31,32,Rajat Bajaj,M,Chennai,67.0,49.0,86.0,202.0,67.33,16.5
32,33,Swati Deshmukh,F,Chennai,36.0,94.0,38.0,168.0,56.00,35.0
33,34,Harsh Vora,F,Mumbai,57.0,64.0,86.0,207.0,69.00,14.0
34,35,Isha Thakur,F,Bengaluru,65.0,67.0,72.0,204.0,68.00,15.0
35,36,Kunal Dutta,M,Bengaluru,76.0,53.0,30.0,159.0,53.00,38.0
36,37,Bhavya Chopra,F,Chennai,54.0,53.0,71.0,178.0,59.33,30.5
37,38,Sameer Ansari,F,Chennai,88.0,82.0,90.0,260.0,86.67,3.0
38,39,Nidhi Bansal,F,Mumbai,51.0,64.0,63.0,178.0,59.33,30.5
39,40,Om Prakash,M,Kolkata,39.0,47.0,59.0,145.0,48.33,44.5
41,42,Bela Shetty,M,Kolkata,32.0,80.0,45.0,157.0,52.33,39.5
42,43,Chirag Rawat,M,Pune,57.0,66.0,48.0,171.0,57.00,34.0
44,45,Eshan Chatterjee,M,Pune,30.0,77.0,57.0,164.0,54.67,36.5
45,46,Falak Hussain,M,Kolkata,48.0,83.0,87.0,218.0,72.67,10.0
46,47,Gauri Nambiar,F,Mumbai,87.0,76.0,64.0,227.0,75.67,6.0
47,48,Hitesh Goyal,F,Pune,91.0,98.0,90.0,279.0,93.00,2.0
48,49,Ira Vaidya,M,Chennai,58.0,52.0,89.0,199.0,66.33,18.0
49,50,Jatin Sood,M,Delhi,48.0,49.0,91.0,188.0,62.67,26.0
50,51,Kiran Bhalla,M,Kolkata,48.0,87.0,45.0,180.0,60.00,29.0
51,52,Lavanya Menon,F,Pune,93.0,98.0,96.0,287.0,95.67,1.0
53,54,Nisha Sharma,F,Bengaluru,64.0,72.0,47.0,183.0,61.00,28.0
55,56,Pallavi Rana,F,Delhi,87.0,69.0,46.0,202.0,67.33,16.5
56,57,Qasim Sheikh,M,Delhi,49.0,55.0,91.0,195.0,65.00,20.0
57,58,Reema Chowdhury,F,Kolkata,61.0,47.0,33.0,141.0,47.00,46.0
58,59,Sahil Kapoor,M,Pune,60.0,59.0,34.0,153.0,51.00,42.0

In [34]:
##pass or fail
import numpy as np 
df_student["Result"] = df_student["Average"].apply(lambda x: "Pass" if x > 40 else "Fail")

df_student

,StudentID,Name,Gender,City,Math,Science,English,Total,Average,Rank,Result
0,1,Aditi Sharma,F,Bengaluru,33.0,33.0,74.0,140.0,46.67,47.5,Pass
1,2,Rohan Verma,F,Mumbai,78.0,97.0,60.0,235.0,78.33,5.0,Pass
2,3,Meera Nair,F,Delhi,90.0,81.0,70.0,241.0,80.33,4.0,Pass
3,4,Karan Mehta,F,Delhi,45.0,41.0,70.0,156.0,52.00,41.0,Pass
4,5,Sneha Rao,M,Delhi,91.0,80.0,51.0,222.0,74.00,7.0,Pass
5,6,Arjun Singh,F,Mumbai,35.0,47.0,63.0,145.0,48.33,44.5,Pass
7,8,Vikram Joshi,F,Delhi,48.0,65.0,83.0,196.0,65.33,19.0,Pass
8,9,Anjali Gupta,F,Bengaluru,49.0,77.0,49.0,175.0,58.33,33.0,Pass
10,11,Divya Menon,M,Mumbai,82.0,45.0,65.0,192.0,64.00,24.0,Pass
11,12,Kabir Malik,F,Mumbai,56.0,85.0,52.0,193.0,64.33,22.5,Pass
12,13,Ishita Bose,F,Chennai,45.0,36.0,83.0,164.0,54.67,36.5,Pass
13,14,Farhan Sheikh,M,Chennai,47.0,93.0,51.0,191.0,63.67,25.0,Pass
15,16,Aman Trivedi,F,Pune,57.0,69.0,68.0,194.0,64.67,21.0,Pass
16,17,Pooja Iyer,M,Chennai,97.0,60.0,64.0,221.0,73.67,8.0,Pass
17,18,Siddharth Rana,M,Kolkata,80.0,39.0,96.0,215.0,71.67,11.0,Pass
18,19,Tanvi Shah,M,Pune,60.0,86.0,73.0,219.0,73.00,9.0,Pass
19,20,Yash Agarwal,F,Bengaluru,47.0,55.0,37.0,139.0,46.33,49.0,Pass
20,21,Ritu Bhatt,M,Kolkata,30.0,70.0,31.0,131.0,43.67,50.0,Pass
22,23,Sanya Khanna,M,Bengaluru,31.0,74.0,52.0,157.0,52.33,39.5,Pass
23,24,Dev Saxena,M,Mumbai,58.0,74.0,61.0,193.0,64.33,22.5,Pass
24,25,Kavya Pillai,F,Kolkata,46.0,31.0,72.0,149.0,49.67,43.0,Pass
25,26,Nikhil Bhatia,M,Kolkata,98.0,47.0,42.0,187.0,62.33,27.0,Pass
26,27,Simran Kaur,M,Mumbai,98.0,66.0,45.0,209.0,69.67,13.0,Pass
28,29,Riya Sinha,F,Pune,64.0,41.0,35.0,140.0,46.67,47.5,Pass
29,30,Varun Oberoi,M,Kolkata,79.0,65.0,69.0,213.0,71.00,12.0,Pass
30,31,Ananya Pandey,F,Mumbai,59.0,54.0,63.0,176.0,58.67,32.0,Pass
31,32,Rajat Bajaj,M,Chennai,67.0,49.0,86.0,202.0,67.33,16.5,Pass
32,33,Swati Deshmukh,F,Chennai,36.0,94.0,38.0,168.0,56.00,35.0,Pass
33,34,Harsh Vora,F,Mumbai,57.0,64.0,86.0,207.0,69.00,14.0,Pass
34,35,Isha Thakur,F,Bengaluru,65.0,67.0,72.0,204.0,68.00,15.0,Pass
35,36,Kunal Dutta,M,Bengaluru,76.0,53.0,30.0,159.0,53.00,38.0,Pass
36,37,Bhavya Chopra,F,Chennai,54.0,53.0,71.0,178.0,59.33,30.5,Pass
37,38,Sameer Ansari,F,Chennai,88.0,82.0,90.0,260.0,86.67,3.0,Pass
38,39,Nidhi Bansal,F,Mumbai,51.0,64.0,63.0,178.0,59.33,30.5,Pass
39,40,Om Prakash,M,Kolkata,39.0,47.0,59.0,145.0,48.33,44.5,Pass
41,42,Bela Shetty,M,Kolkata,32.0,80.0,45.0,157.0,52.33,39.5,Pass
42,43,Chirag Rawat,M,Pune,57.0,66.0,48.0,171.0,57.00,34.0,Pass
44,45,Eshan Chatterjee,M,Pune,30.0,77.0,57.0,164.0,54.67,36.5,Pass
45,46,Falak Hussain,M,Kolkata,48.0,83.0,87.0,218.0,72.67,10.0,Pass
46,47,Gauri Nambiar,F,Mumbai,87.0,76.0,64.0,227.0,75.67,6.0,Pass
47,48,Hitesh Goyal,F,Pune,91.0,98.0,90.0,279.0,93.00,2.0,Pass
48,49,Ira Vaidya,M,Chennai,58.0,52.0,89.0,199.0,66.33,18.0,Pass
49,50,Jatin Sood,M,Delhi,48.0,49.0,91.0,188.0,62.67,26.0,Pass
50,51,Kiran Bhalla,M,Kolkata,48.0,87.0,45.0,180.0,60.00,29.0,Pass
51,52,Lavanya Menon,F,Pune,93.0,98.0,96.0,287.0,95.67,1.0,Pass
53,54,Nisha Sharma,F,Bengaluru,64.0,72.0,47.0,183.0,61.00,28.0,Pass
55,56,Pallavi Rana,F,Delhi,87.0,69.0,46.0,202.0,67.33,16.5,Pass
56,57,Qasim Sheikh,M,Delhi,49.0,55.0,91.0,195.0,65.00,20.0,Pass
57,58,Reema Chowdhury,F,Kolkata,61.0,47.0,33.0,141.0,47.00,46.0,Pass
58,59,Sahil Kapoor,M,Pune,60.0,59.0,34.0,153.0,51.00,42.0,Pass

In [36]:
##Gender and city wise analysis

report = df_student.groupby(["City", "Gender"])["Average"].agg(["sum", "max", "min", "mean"])
report

                     sum    max    min       mean
City      Gender
Bengaluru F       280.33  68.00  46.33  56.066000
          M       105.33  53.00  52.33  52.665000
Chennai   F       256.67  86.67  54.67  64.167500
          M       271.00  73.67  63.67  67.750000
Delhi     F       264.99  80.33  52.00  66.247500
          M       201.67  74.00  62.67  67.223333
Kolkata   F        96.67  49.67  47.00  48.335000
          M       482.00  72.67  43.67  60.250000
Mumbai    F       453.66  78.33  48.33  64.808571
          M       198.00  69.67  64.00  66.000000
Pune      F       300.01  95.67  46.67  75.002500
          M       235.67  73.00  51.00  58.917500

In [37]:
##Combined group by report

report1 = df_student.groupby(["City", "Gender"]).agg({
    "Math": ["sum", "max", "min", "mean"],
    "Science": ["sum", "max", "min", "mean"],
    "Average": ["sum", "max", "min", "mean"]
})

report1

                   Math                        Science                         \
                    sum   max   min       mean     sum   max   min       mean
City      Gender
Bengaluru F       258.0  65.0  33.0  51.600000   304.0  77.0  33.0  60.800000
          M       107.0  76.0  31.0  53.500000   127.0  74.0  53.0  63.500000
Chennai   F       223.0  88.0  36.0  55.750000   265.0  94.0  36.0  66.250000
          M       269.0  97.0  47.0  67.250000   254.0  93.0  49.0  63.500000
Delhi     F       270.0  90.0  45.0  67.500000   256.0  81.0  41.0  64.000000
          M       188.0  91.0  48.0  62.666667   184.0  80.0  49.0  61.333333
Kolkata   F       107.0  61.0  46.0  53.500000    78.0  47.0  31.0  39.000000
          M       454.0  98.0  30.0  56.750000   518.0  87.0  39.0  64.750000
Mumbai    F       423.0  87.0  35.0  60.428571   487.0  97.0  47.0  69.571429
          M       238.0  98.0  58.0  79.333333   185.0  74.0  45.0  61.666667
Pune      F       305.0  93.0  57.0  76.250000   306.0  98.0  41.0  76.500000
          M       207.0  60.0  30.0  51.750000   288.0  86.0  59.0  72.000000

                 Average
                     sum    max    min       mean
City      Gender
Bengaluru F       280.33  68.00  46.33  56.066000
          M       105.33  53.00  52.33  52.665000
Chennai   F       256.67  86.67  54.67  64.167500
          M       271.00  73.67  63.67  67.750000
Delhi     F       264.99  80.33  52.00  66.247500
          M       201.67  74.00  62.67  67.223333
Kolkata   F        96.67  49.67  47.00  48.335000
          M       482.00  72.67  43.67  60.250000
Mumbai    F       453.66  78.33  48.33  64.808571
          M       198.00  69.67  64.00  66.000000
Pune      F       300.01  95.67  46.67  75.002500
          M       235.67  73.00  51.00  58.917500

In [38]:
##Topper list

top_10 = df_student[df_student["Rank"] <= 10]
top_10

,StudentID,Name,Gender,City,Math,Science,English,Total,Average,Rank,Result
1,2,Rohan Verma,F,Mumbai,78.0,97.0,60.0,235.0,78.33,5.0,Pass
2,3,Meera Nair,F,Delhi,90.0,81.0,70.0,241.0,80.33,4.0,Pass
4,5,Sneha Rao,M,Delhi,91.0,80.0,51.0,222.0,74.00,7.0,Pass
16,17,Pooja Iyer,M,Chennai,97.0,60.0,64.0,221.0,73.67,8.0,Pass
18,19,Tanvi Shah,M,Pune,60.0,86.0,73.0,219.0,73.00,9.0,Pass
37,38,Sameer Ansari,F,Chennai,88.0,82.0,90.0,260.0,86.67,3.0,Pass
45,46,Falak Hussain,M,Kolkata,48.0,83.0,87.0,218.0,72.67,10.0,Pass
46,47,Gauri Nambiar,F,Mumbai,87.0,76.0,64.0,227.0,75.67,6.0,Pass
47,48,Hitesh Goyal,F,Pune,91.0,98.0,90.0,279.0,93.00,2.0,Pass
51,52,Lavanya Menon,F,Pune,93.0,98.0,96.0,287.0,95.67,1.0,Pass

In [42]:
##Exporting the final report


top_10.to_csv("top_10_students.csv", index=False)