In [23]:
import pandas as pd

In [4]:
df_student = pd.read_csv(r"C:\Users\anmol\Downloads\students_clean.csv")
df_student

    StudentID       Name Gender     City    JoinDate  Math  Science  English
0           1      Aditi      M    Delhi  2024-01-10  95.0     63.0     98.0
1           2      Rohan      F  Chennai  2024-01-19  62.0     77.0     77.0
2           3      Meera      F  Chennai  2024-01-28  45.0     76.0     61.0
3           4      Karan      M   Mumbai  2024-02-06  66.6     65.0     61.0
4           5      Sneha      M    Delhi  2024-02-15  75.0     89.0     61.0
5           6      Arjun      F  Kolkata  2024-02-24  79.0     71.0     87.0
6           7      Priya      M     Pune  2024-03-04  41.0     40.0     55.0
7           8     Vikram      F  Kolkata  2024-03-13  54.0     83.0     45.0
8           9     Anjali      M  Chennai  2024-03-22  84.0     66.2     56.0
9          10      Rahul      M  Chennai  2024-03-31  88.0     75.0     36.0
10         11      Divya      F  Chennai  2024-04-09  62.0     71.0     41.0
11         12      Kabir      F    Delhi  2024-04-18  86.0     70.0     40.0
12         13     Ishita      F   Mumbai  2024-04-27  88.0     40.0     64.9
13         14     Farhan      F     Pune  2024-05-06  59.0     70.0     81.0
14         15       Neha      F     Pune  2024-05-15  92.0     85.0     79.0
15         16       Aman      F    Delhi  2024-05-24  53.0     54.0     64.0
16         17      Pooja      F     Pune  2024-06-02  50.0     73.0     80.0
17         18  Siddharth      M    Delhi  2024-06-11  66.6     36.0     45.0
18         19      Tanvi      F  Chennai  2024-06-20  75.0     57.0     92.0
19         20       Yash      M  Chennai  2024-06-29  43.0     62.0     67.0
20         21       Ritu      F  Kolkata  2024-07-08  88.0     97.0     95.0
21         22      Manav      M  Chennai  2024-07-17  47.0     48.0     44.0
22         23      Sanya      M   Mumbai  2024-07-26  86.0     52.0     66.0
23         24        Dev      F  Kolkata  2024-08-04  35.0     61.0     79.0
24         25      Kavya      F     Pune  2024-08-13  85.0     98.0     66.0
25         26     Nikhil      F   Mumbai  2024-08-22  85.0     66.2     63.0
26         27     Simran      M  Kolkata  2024-08-31  84.0     37.0     45.0
27         28      Aryan      F   Mumbai  2024-09-09  77.0     49.0     59.0
28         29       Riya      F    Delhi  2024-09-18  65.0     87.0     50.0
29         30      Varun      M     Pune  2024-09-27  66.6     38.0     54.0
30         31     Ananya      M  Chennai  2024-10-06  52.0     89.0     78.0
31         32      Rajat      M    Delhi  2024-10-15  84.0     53.0     75.0
32         33      Swati      M     Pune  2024-10-24  70.0     93.0     73.0
33         34      Harsh      F    Delhi  2024-11-02  64.0     53.0     64.9
34         35       Isha      F  Chennai  2024-11-11  67.0     62.0     96.0
35         36      Kunal      M     Pune  2024-11-20  71.0     77.0     40.0
36         37     Bhavya      F   Mumbai  2024-11-29  37.0     43.0     64.9
37         38     Sameer      F   Mumbai  2024-12-08  43.0     70.0     42.0
38         39      Nidhi      M     Pune  2024-12-17  50.0     67.0     56.0
39         40         Om      F  Chennai  2024-12-26  42.0     85.0     96.0

In [6]:
df_student.groupby("City")["Math"].mean().round(2)

City
Chennai    60.64
Delhi      73.58
Kolkata    68.00
Mumbai     68.94
Pune       64.96
Name: Math, dtype: float64

In [7]:
df_student.groupby("City")["Math"].agg(["count", "min", "max", "median", "std"]).round(2)

         count   min   max  median    std
City
Chennai     11  42.0  88.0    62.0  16.46
Delhi        8  53.0  95.0    70.8  13.95
Kolkata      5  35.0  88.0    79.0  22.70
Mumbai       7  37.0  88.0    77.0  21.12
Pune         9  41.0  92.0    66.6  16.79

In [10]:
report = df_student.groupby("City").agg(
    total_math = ("Math", "sum"),
    avg_math = ("Math", "mean"),
    students = ("Math", "count")
).round(2)
print(report)

         total_math  avg_math  students
City
Chennai       667.0     60.64        11
Delhi         588.6     73.58         8
Kolkata       340.0     68.00         5
Mumbai        482.6     68.94         7
Pune          584.6     64.96         9

In [12]:
df_student.groupby(["City", "Gender"])["Math"].mean().round(2)

City     Gender
Chennai  F         58.83
         M         62.80
Delhi    F         67.00
         M         80.15
Kolkata  F         64.00
         M         84.00
Mumbai   F         66.00
         M         76.30
Pune     F         71.50
         M         59.72
Name: Math, dtype: float64

In [13]:
df_student.groupby(["City", "Gender"])["Math"].agg(["count", "min", "max", "median", "std"]).round(2)

                count   min   max  median    std
City    Gender
Chennai F           6  42.0  75.0    62.0  12.83
        M           5  43.0  88.0    52.0  21.46
Delhi   F           4  53.0  86.0    64.5  13.78
        M           4  66.6  95.0    79.5  12.19
Kolkata F           4  35.0  88.0    66.5  24.10
        M           1  84.0  84.0    84.0    NaN
Mumbai  F           5  37.0  88.0    77.0  24.17
        M           2  66.6  86.0    76.3  13.72
Pune    F           4  50.0  92.0    72.0  20.17
        M           5  41.0  71.0    66.6  13.46

In [14]:
report1 = df_student.groupby(["City", "Gender"]).agg(
    total_math = ("Math", "sum"),
    avg_math = ("Math", "mean"),
    students = ("Math", "count")
).round(2)
print(report1)

                total_math  avg_math  students
City    Gender
Chennai F            353.0     58.83         6
        M            314.0     62.80         5
Delhi   F            268.0     67.00         4
        M            320.6     80.15         4
Kolkata F            256.0     64.00         4
        M             84.0     84.00         1
Mumbai  F            330.0     66.00         5
        M            152.6     76.30         2
Pune    F            286.0     71.50         4
        M            298.6     59.72         5

In [ ]:
##goupby :-> split and apply and then combine

In [24]:
df_customers = pd.read_csv(r"C:\Users\anmol\Downloads\customers.csv")

df_customers

   CustID          Name     City
0     101    Ananya Rao    Delhi
1     102    Bilal Khan   Mumbai
2     103   Chitra Iyer     Pune
3     104  Dev Malhotra  Chennai
4     105   Esha Kapoor  Kolkata
5     106  Faisal Ahmed    Delhi

In [25]:
df_orders = pd.read_csv(r"C:\Users\anmol\Downloads\orders.csv")

df_orders

   OrderID  CustID     Product  Amount   OrderDate
0     1001     101      Laptop   55000  2026-01-05
1     1002     102  Headphones    2500  2026-01-08
2     1003     102     Monitor    9800  2026-01-15
3     1004     104    Keyboard    1200  2026-02-02
4     1005     107      Webcam    3200  2026-02-10
5     1006     101       Mouse     700  2026-02-14
6     1007     108      Tablet   21000  2026-03-01

In [26]:
df_sales = pd.read_csv(r"C:\Users\anmol\Downloads\sales.csv")

df_sales

      OrderDate Region       Store       Product     Category  Units  Revenue
0    2026-01-07   East       Patna     Desk Lamp  Electronics      1      900
1    2026-01-07  North  Chandigarh     Desk Lamp  Electronics      4      600
2    2026-01-09  North  Chandigarh     Desk Lamp  Electronics     15    18000
3    2026-01-11   East       Patna      Backpack  Accessories     19     2850
4    2026-01-12   West      Mumbai       Pen Set   Stationery      6     7200
..          ...    ...         ...           ...          ...    ...      ...
175  2026-06-23   East       Patna  Water Bottle  Accessories      6     2400
176  2026-06-23   West        Pune     Desk Lamp  Electronics     22    13200
177  2026-06-24  North       Delhi  Water Bottle  Accessories     24     6000
178  2026-06-28   East       Patna      Backpack  Accessories     23     9200
179  2026-06-29  North  Chandigarh  Water Bottle  Accessories     19    17100

[180 rows x 7 columns]

In [30]:
jan = df_orders[df_orders["OrderDate"] < "2026-02-01"]
feb = df_orders[df_orders["OrderDate"] >= "2026-02-01"]

all_orders = pd.concat([jan, feb], axis = 0, ignore_index = True)
print(all_orders)
print(all_orders.shape)

   OrderID  CustID     Product  Amount   OrderDate
0     1001     101      Laptop   55000  2026-01-05
1     1002     102  Headphones    2500  2026-01-08
2     1003     102     Monitor    9800  2026-01-15
3     1004     104    Keyboard    1200  2026-02-02
4     1005     107      Webcam    3200  2026-02-10
5     1006     101       Mouse     700  2026-02-14
6     1007     108      Tablet   21000  2026-03-01
(7, 5)

In [32]:
print(pd.merge(df_orders, df_customers, on ="CustID", how = "inner"))

   OrderID  CustID     Product  Amount   OrderDate          Name     City
0     1001     101      Laptop   55000  2026-01-05    Ananya Rao    Delhi
1     1002     102  Headphones    2500  2026-01-08    Bilal Khan   Mumbai
2     1003     102     Monitor    9800  2026-01-15    Bilal Khan   Mumbai
3     1004     104    Keyboard    1200  2026-02-02  Dev Malhotra  Chennai
4     1006     101       Mouse     700  2026-02-14    Ananya Rao    Delhi

In [34]:
print(df_orders.set_index("CustID").join(df_customers.set_index("CustID"), how = "left").head())

        OrderID     Product  Amount   OrderDate          Name     City
CustID
101        1001      Laptop   55000  2026-01-05    Ananya Rao    Delhi
102        1002  Headphones    2500  2026-01-08    Bilal Khan   Mumbai
102        1003     Monitor    9800  2026-01-15    Bilal Khan   Mumbai
104        1004    Keyboard    1200  2026-02-02  Dev Malhotra  Chennai
107        1005      Webcam    3200  2026-02-10           NaN      NaN